name: React Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ... (unchanged steps for build)

  zip_and_deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # ... (unchanged steps for zip_and_deploy)

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: 202.176.1.150
          port: 22
          username: server
          password: sanjeev123
          scp_source: ${{ github.workspace }}/archive.zip
          scp_target: /media/server/data-5121/laye

  unzip_on_server:
    runs-on: ubuntu-latest
    needs: zip_and_deploy

    steps:
      - name: SSH Unzip on Server
        uses: appleboy/ssh-action@v0
        with:
          host: 202.176.1.150
          username: server
          password: sanjeev123
          script: |
            cd /media/server/data-5121/laye
            unzip -q archive.zip -d /media/server/data-5121/laye
